# Generated by Django 4.0.5 on 2022-06-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coords',
            old_name='ongitude',
            new_name='longitude',
        ),
    ]
