# Generated by Django 4.0.5 on 2022-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ongitude_coords_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.TextField(),
        ),
    ]
