# Generated by Django 4.0.5 on 2022-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladd',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
