# Generated by Django 4.0.5 on 2022-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_perevaladd_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladd',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='NEW', max_length=10),
        ),
    ]
