# Generated by Django 4.0.5 on 2022-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_perevaladd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(max_length=255),
        ),
    ]
