# Generated by Django 4.0.5 on 2022-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='perevaladd',
            options={'verbose_name_plural': 'Перевалы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(max_length=255, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(max_length=255, verbose_name='Долгота'),
        ),
    ]
