# Generated by Django 4.0.5 on 2022-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_activitiestypes_perevalareas_alter_coords_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladd',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
    ]
